# About
These are my personal notes on the *julia_for_pythonistas_source*

## Estimating π
Also tried this function in a python kernel and is sensibly faster (without timing it)

In [2]:
function estimate_pi(n)
    s = 1.0
    for i in 1:n
        s += (isodd(i) ? -1 : 1) / (2i + 1)
    end
    4s
end

estimate_pi(100_000_000)

3.141592663589326

## Typing Unicode Characters
This is simply great 😎

## Using Plots
Inside *Runing python code in Julia,* the julia library `Plots` is mentioned. Have checked out its [page](http://docs.juliaplots.org/latest/) and appears a beautiful animation of Lorenz attractor that is pasted here:

In [ ]:
using Plots
# define the Lorenz attractor
Base.@kwdef mutable struct Lorenz
    dt::Float64 = 0.02
    σ::Float64 = 10
    ρ::Float64 = 28
    β::Float64 = 8/3
    x::Float64 = 1
    y::Float64 = 1
    z::Float64 = 1
end

function step!(l::Lorenz)
    dx = l.σ * (l.y - l.x);         l.x += l.dt * dx
    dy = l.x * (l.ρ - l.z) - l.y;   l.y += l.dt * dy
    dz = l.x * l.y - l.β * l.z;     l.z += l.dt * dz
end

attractor = Lorenz()


# initialize a 3D plot with 1 empty series
plt = plot3d(
    1,
    xlim = (-30, 30),
    ylim = (-30, 30),
    zlim = (0, 60),
    title = "Lorenz Attractor",
    marker = 2,
)

# build an animated gif by pushing new points to the plot, saving every 10th frame
@gif for i=1:1500
    step!(attractor)
    push!(plt, attractor.x, attractor.y, attractor.z)
end every 10

## Multidimensional arrays
What a nice visualization of the matrix not like with numpy with all those brackets everywhere

In [7]:
M = [1 2 3
     4 5 6
     7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [10]:
# The colon adds a new row
[1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

This math notation is so cool
* `a ∉ b` is equivalent to `!(a in b)` (or `a not in b` in Python). You can type `∉` with `\notin<tab>`
* `a ∈ b` is equivalent to `a in b`. You can type it with `\in<tab>`
* ∪ is the union symbol, not a U. To type this character, type `\cup<tab>` (it has the shape of a cup)
* Now let's get the intersection using the ∩ symbol (type `\cap<tab>`):

In [15]:
[1 for _ in 1:3, _ in 1:5]

3×5 Array{Int64,2}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

## Annonymous functions 

In [6]:
function my_for(func, collection)
    for i in collection
        func(i)
    end
end

# In this case `do`, that points to `println`, represents the function arg in 
# `my_for`, whereas `1:4` is the collection.
my_for(1:4) do i
    println("The square of $i is $(i^2)")
end

The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
