# About
These are my personal notes on the *julia_for_pythonistas_source*

## Estimating π
Also tried this function in a python kernel and is sensibly faster (without timing it)

In [2]:
function estimate_pi(n)
    s = 1.0
    for i in 1:n
        s += (isodd(i) ? -1 : 1) / (2i + 1)
    end
    4s
end

estimate_pi(100_000_000)

3.141592663589326

## Typing Unicode Characters
This is simply great 😎

## Using Plots
Inside *Runing python code in Julia,* the julia library `Plots` is mentioned. Have checked out its [page](http://docs.juliaplots.org/latest/) and appears a beautiful animation of Lorenz attractor that is pasted here:

In [ ]:
using Plots
# define the Lorenz attractor
Base.@kwdef mutable struct Lorenz
    dt::Float64 = 0.02
    σ::Float64 = 10
    ρ::Float64 = 28
    β::Float64 = 8/3
    x::Float64 = 1
    y::Float64 = 1
    z::Float64 = 1
end

function step!(l::Lorenz)
    dx = l.σ * (l.y - l.x);         l.x += l.dt * dx
    dy = l.x * (l.ρ - l.z) - l.y;   l.y += l.dt * dy
    dz = l.x * l.y - l.β * l.z;     l.z += l.dt * dz
end

attractor = Lorenz()


# initialize a 3D plot with 1 empty series
plt = plot3d(
    1,
    xlim = (-30, 30),
    ylim = (-30, 30),
    zlim = (0, 60),
    title = "Lorenz Attractor",
    marker = 2,
)

# build an animated gif by pushing new points to the plot, saving every 10th frame
@gif for i=1:1500
    step!(attractor)
    push!(plt, attractor.x, attractor.y, attractor.z)
end every 10

## Multidimensional arrays
What a nice visualization of the matrix not like with numpy with all those brackets everywhere

In [7]:
M = [1 2 3
     4 5 6
     7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [10]:
# The colon adds a new row
[1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

This math notation is so cool
* `a ∉ b` is equivalent to `!(a in b)` (or `a not in b` in Python). You can type `∉` with `\notin<tab>`
* `a ∈ b` is equivalent to `a in b`. You can type it with `\in<tab>`
* ∪ is the union symbol, not a U. To type this character, type `\cup<tab>` (it has the shape of a cup)
* Now let's get the intersection using the ∩ symbol (type `\cap<tab>`):

In [1]:
[1 for _ in 1:3, _ in 1:5]

3×5 Array{Int64,2}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

## Annonymous functions 

In [6]:
function my_for(func, collection)
    for i in collection
        func(i)
    end
end

# In this case `do`, that points to `println`, represents the function arg in 
# `my_for`, whereas `1:4` is the collection.
my_for(1:4) do i
    println("The square of $i is $(i^2)")
end

## Event-driven code
This is a bit tricky, actually I had to ask in [Stack overflow](https://stackoverflow.com/questions/63010061/annonymous-functions-and-foreach-usage-on-event-driven-code-in-julia) to make sense of it. I swapped a bit the order of statements to get them in a more natural way.

In [1]:
# Intialize the array
handlers = []

# Define on_click() that will store handler argument in handlers.
on_click(handler) = push!(handlers, handler)

# Store a couple of annonymous functions in the array based on on_click() 
# so later can be called by click()
on_click() do event
    println("Mouse clicked at $event")
end

on_click() do event
    println("Beep.")
end

# Define click function, that will run each of the annonymous functions stored
# in the array and run them with the event argument
click(event) = foreach(handler->handler(event), handlers)

# Finally, trigger the action. Call click, that opens the array and runs the
# functions within it with the arguments provided.
click((x=50, y=20))
click((x=120, y=10))

Mouse clicked at (x = 50, y = 20)
Beep.
Mouse clicked at (x = 120, y = 10)
Beep.


## Context Managers
Basically, it seems, that you if the first argument of a function is yet another function you can pass it by using `do` statement as an annonymous function.

In [5]:
function with_database(func, name)
    println("Opening connection to database $name")
    db = "a db object for database $name"
    try
        func(db)
    finally
        println("Closing connection to database $name")
    end
end

with_database("jobs") do db
    println("I'm working with $db")
    # error("Oops") # try uncommenting this line
end

Opening connection to database jobs
I'm working with a db object for database jobs
Closing connection to database jobs


In [14]:
function foo(f, fancy_arg_of_foo)
    println("Starting foo with $fancy_arg_of_foo")
    f("Annonymous-function's-fancy-arg.")
end

foo("Foo's-fancy-arg") do fancy_arg_of_annonymous
    println(
        "And this is the annonymous function using $fancy_arg_of_annonymous")
end


Starting foo with Foo's-fancy-arg
And this is the annonymous function using Annonymous-function's-fancy-arg.
